Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,9 @@ jobs:
 
     - name: Install EAS CLI
       run: yarn add @expo/eas-build-job # install EAS CLI using Yarn
+      
+    - name: Check EAS CLI
+      run: npx eas --version || echo "EAS CLI not found" # check if EAS CLI is installed
 
     - name: Install dependencies
       run: yarn install # install dependencies using Yarn
